import { readFile } from "node:fs/promises";
import { join } from "node:path";

const ROADMAP_PATH = join(process.cwd(), "docs", "strategy", "roadmap.md");
const STATUS_PATH = join(process.cwd(), "content", "roadmap-status.json");

export type EpicState = "shipped" | "in_progress" | "planned";

const EPIC_STATES: readonly EpicState[] = ["shipped", "in_progress", "planned"];

export interface EpicStatus {
  state: EpicState;
  openIssues: number;
  closedIssues: number;
}

/**
 * One epic, carrying ONLY its id, title and derived status. There is no
 * `body` field anywhere on this type — that is deliberate, not an
 * oversight. `docs/strategy/roadmap.md` is an internal planning document in
 * a public repository, and its epic bodies (Epic 2.7 most sharply) name
 * unfixed defect classes, issue numbers, schema internals and file paths
 * that must never reach a public page. Rather than rely on the renderer to
 * remember not to print the body, `parseRoadmapStructure` below never reads
 * it into memory as anything but discarded prose — the page is structurally
 * incapable of leaking it because the data it holds does not contain it.
 */
export interface RoadmapEpic {
  id: string;
  title: string;
  /** `null` when no status entry exists for this epic — render as unavailable, never as "planned". */
  status: EpicStatus | null;
}

export interface RoadmapPhase {
  name: string;
  epics: RoadmapEpic[];
}

export interface Roadmap {
  phases: RoadmapPhase[];
  /**
   * False when `content/roadmap-status.json` was missing, unreadable, or not
   * shaped like the status generator's output. The page must render the
   * phase/epic structure regardless and say status is unavailable — never
   * crash, and never let every epic silently read as "planned".
   */
  statusAvailable: boolean;
}

// Mirrors scripts/roadmap-status.ts's EPIC_TITLE_PATTERN: accepts an em dash
// or a plain hyphen between the epic number and its name.
const PHASE_PATTERN = /^##\s+Phase\s+\d+\s+[—-]\s+(.+)$/u;
const EPIC_PATTERN = /^###\s+Epic\s+(\d+\.\d+)\s+[—-]\s+(.+)$/u;

/**
 * Extracts phase and epic HEADINGS ONLY from the roadmap markdown — nothing
 * that appears between two headings is ever captured or returned. This is a
 * line-oriented scan specifically so that an epic's body (bullet lists,
 * prose, code blocks, tables) can never end up on an `EpicPhase`/`RoadmapEpic`
 * value, no matter how sensitive a future epic's body turns out to be.
 *
 * Epic headings encountered before any phase heading are dropped (there is
 * no phase to attach them to) rather than thrown away silently as an error —
 * the roadmap format guarantees phases precede their epics, so this is a
 * defensive fallback, not an expected path.
 */
export function parseRoadmapStructure(markdown: string): RoadmapPhase[] {
  const phases: RoadmapPhase[] = [];
  let current: RoadmapPhase | null = null;

  for (const rawLine of markdown.split("\n")) {
    const line = rawLine.trim();

    const phaseMatch = PHASE_PATTERN.exec(line);
    if (phaseMatch) {
      current = { name: phaseMatch[1]!.trim(), epics: [] };
      phases.push(current);
      continue;
    }

    const epicMatch = EPIC_PATTERN.exec(line);
    if (epicMatch && current) {
      current.epics.push({ id: epicMatch[1]!, title: epicMatch[2]!.trim(), status: null });
    }
  }

  return phases;
}

function isEpicState(value: unknown): value is EpicState {
  return typeof value === "string" && (EPIC_STATES as readonly string[]).includes(value);
}

/**
 * Parses the status generator's JSON output into a lookup by epic id.
 * Anything not shaped exactly like an `EpicStatus` entry (missing/bad
 * `epic`, an unrecognised `state`, ...) is skipped rather than trusted —
 * stale or hand-edited status data must degrade to "unavailable" for that
 * entry, not crash the page or misreport a state.
 */
export function parseEpicStatuses(json: unknown): Map<string, EpicStatus> {
  const statuses = new Map<string, EpicStatus>();
  if (!Array.isArray(json)) return statuses;

  for (const entry of json) {
    if (typeof entry !== "object" || entry === null) continue;
    const record = entry as Record<string, unknown>;
    if (typeof record.epic !== "string" || !isEpicState(record.state)) continue;

    statuses.set(record.epic, {
      state: record.state,
      openIssues: typeof record.openIssues === "number" ? record.openIssues : 0,
      closedIssues: typeof record.closedIssues === "number" ? record.closedIssues : 0,
    });
  }

  return statuses;
}

/**
 * Reads `content/roadmap-status.json` — a committed artifact regenerated by
 * running `pnpm --silent roadmap:status` (see package.json's
 * `roadmap:status:generate`), not fetched from GitHub on every page view.
 * See `loadRoadmap`'s doc comment for why.
 *
 * Never throws: a missing file, invalid JSON, or a payload that isn't the
 * expected array all resolve to `{ statuses: empty map, available: false }`
 * so the page can render the roadmap structure with an honest "status
 * unavailable" instead of crashing.
 */
export async function loadEpicStatuses(): Promise<{
  statuses: Map<string, EpicStatus>;
  available: boolean;
}> {
  try {
    const raw = await readFile(STATUS_PATH, "utf8");
    const parsed: unknown = JSON.parse(raw);
    if (!Array.isArray(parsed)) return { statuses: new Map(), available: false };
    return { statuses: parseEpicStatuses(parsed), available: true };
  } catch {
    return { statuses: new Map(), available: false };
  }
}

/**
 * Builds the full roadmap view model: phase/epic structure parsed from
 * `docs/strategy/roadmap.md`, each epic paired with its status from the
 * committed status artifact.
 *
 * Status data source, and why it is not fetched live: `scripts/roadmap-status.ts`
 * shells out to `gh api` and throws if GitHub is unreachable — exactly the
 * right behaviour for a script a human or CI runs and inspects, and exactly
 * the wrong behaviour for a public page's render path (a GitHub outage, rate
 * limit, or missing `gh` auth on the server would either 500 the page or
 * require bundling `gh` credentials into the deployment). Instead the
 * generator's output is committed to `content/roadmap-status.json` — the
 * same treatment `content/changelog/*.mdx` already gets — and regenerated
 * out of band (`pnpm --silent roadmap:status:generate`, run by a maintainer
 * or a scheduled CI job) whenever milestones change. This loader only ever
 * reads that committed file from disk, at request time, exactly like
 * `src/lib/changelog.ts` reads its MDX files from disk.
 */
export async function loadRoadmap(): Promise<Roadmap> {
  const markdown = await readFile(ROADMAP_PATH, "utf8");
  const phases = parseRoadmapStructure(markdown);
  const { statuses, available } = await loadEpicStatuses();

  for (const phase of phases) {
    for (const epic of phase.epics) {
      epic.status = statuses.get(epic.id) ?? null;
    }
  }

  return { phases, statusAvailable: available };
}
