version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: historian_postgres_staging
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_USER: ${MYSQL_USER}
      POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - historian_staging_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: historian_app_staging
    restart: unless-stopped
    env_file:
      - .env.staging
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - strapi
    networks:
      - historian_staging_network
    volumes:
      - ./logs/staging:/app/logs

  strapi:
    image: strapi/strapi:5.18.0
    container_name: historian_strapi_staging
    restart: unless-stopped
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=staging
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USERNAME=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "1338:1337"
    depends_on:
      - postgres
    networks:
      - historian_staging_network
    volumes:
      - ./logs/staging:/opt/app/logs
      - ./uploads/staging:/opt/app/public/uploads

  nginx:
    image: nginx:alpine
    container_name: historian_nginx_staging
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./ssl:/etc/nginx/ssl
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
      - strapi
    networks:
      - historian_staging_network

volumes:
  postgres_staging_data:

networks:
  historian_staging_network:
    driver: bridge 