version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: historian_postgres_staging
    restart: unless-stopped
    environment:
      POSTGRES_DB: historian_staging
      POSTGRES_USER: historian_staging
      POSTGRES_PASSWORD: staging_password
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - historian_staging_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: historian_app_staging
    restart: unless-stopped
    environment:
      - NODE_ENV=staging
      - DATABASE_URL=postgresql://historian_staging:staging_password@postgres:5432/historian_staging
      - NEXT_PUBLIC_APP_URL=https://staging.evidoxa.com
      - NEXT_PUBLIC_STRAPI_URL=https://staging.evidoxa.com
      # ...other env vars as in production
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - strapi
    networks:
      - historian_staging_network
    volumes:
      - ./logs/staging:/app/logs

  strapi:
    image: strapi/strapi:5.18.0
    container_name: historian_strapi_staging
    restart: unless-stopped
    environment:
      - NODE_ENV=staging
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=historian_staging
      - DATABASE_USERNAME=historian_staging
      - DATABASE_PASSWORD=staging_password
      # ...other Strapi env vars as in production
    ports:
      - "1338:1337"
    depends_on:
      - postgres
    networks:
      - historian_staging_network
    volumes:
      - ./logs/staging:/opt/app/logs
      - ./uploads/staging:/opt/app/public/uploads

  nginx:
    image: nginx:alpine
    container_name: historian_nginx_staging
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./ssl:/etc/nginx/ssl
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
      - strapi
    networks:
      - historian_staging_network

volumes:
  postgres_staging_data:

networks:
  historian_staging_network:
    driver: bridge 