services:
  postgres:
    image: postgres:15
    container_name: historian_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: historian
      POSTGRES_USER: historian
      POSTGRES_PASSWORD: historian
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - historian_network

  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    container_name: historian_strapi
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: historian
      DATABASE_USERNAME: historian
      DATABASE_PASSWORD: historian
      DATABASE_SSL: "false"


    ports:
      - "1337:1337"
    depends_on:
      - postgres
    command: yarn develop --debug
    volumes:
      - strapi_uploads:/opt/app/public/uploads
    networks:
      - historian_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL
        - DATABASE_URL_UNPOOLED
    container_name: historian_app
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=postgres://historian:historian@postgres:5432/historian
      - DATABASE_URL_UNPOOLED=postgres://historian:historian@postgres:5432/historian
      - PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
      # ...other env vars...
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - strapi
    volumes:
      - ./prisma:/app/prisma
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    command: sh -c "npx prisma db push --accept-data-loss && node server.js"
    networks:
      - historian_network

volumes:
  pg_data:
  strapi_uploads:

networks:
  historian_network:
    driver: bridge 