name: Deploy to Staging

on:
  push:
    branches:
      - development

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy files to VPS
        run: |
          rsync -avz --exclude '.git' ./ root@217.154.198.215:/opt/historian-app/staging

      - name: Write .env.staging on server
        run: |
          ssh root@217.154.198.215 "echo 'NODE_ENV=staging' > /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'DATABASE_URL_UNPOOLED=${{ secrets.STAGING_DATABASE_URL_UNPOOLED }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'DATABASE_HOST=${{ secrets.STAGING_DATABASE_HOST }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'DATABASE_PORT=${{ secrets.STAGING_DATABASE_PORT }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'DATABASE_NAME=${{ secrets.STAGING_DATABASE_NAME }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'DATABASE_USERNAME=${{ secrets.STAGING_DATABASE_USERNAME }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'DATABASE_PASSWORD=${{ secrets.STAGING_DATABASE_PASSWORD }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'JWT_SECRET=${{ secrets.STAGING_JWT_SECRET }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'NEXT_PUBLIC_APP_URL=${{ secrets.STAGING_NEXT_PUBLIC_APP_URL }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'NEXT_PUBLIC_STRAPI_URL=${{ secrets.STAGING_NEXT_PUBLIC_STRAPI_URL }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'WORKOS_API_KEY=${{ secrets.STAGING_WORKOS_API_KEY }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'WORKOS_CLIENT_ID=${{ secrets.STAGING_WORKOS_CLIENT_ID }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'WORKOS_REDIRECT_URI=${{ secrets.STAGING_WORKOS_REDIRECT_URI }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'WORKOS_COOKIE_PASSWORD=${{ secrets.STAGING_WORKOS_COOKIE_PASSWORD }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'REDIS_PASSWORD=${{ secrets.STAGING_REDIS_PASSWORD }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'APP_KEYS=${{ secrets.STAGING_APP_KEYS }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'ENCRYPTION_KEY=${{ secrets.STAGING_ENCRYPTION_KEY }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'REDIS_URL=${{ secrets.STAGING_REDIS_URL }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'ADMIN_JWT_SECRET=${{ secrets.STAGING_ADMIN_JWT_SECRET }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'ADMIN_API_TOKEN_SALT=${{ secrets.STAGING_ADMIN_API_TOKEN_SALT }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'AUTHKIT_REDIRECT_URI=${{ secrets.STAGING_AUTHKIT_REDIRECT_URI }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'DOMAIN=${{ secrets.STAGING_DOMAIN }}' >> /opt/historian-app/staging/.env.staging"
          ssh root@217.154.198.215 "echo 'SSL_EMAIL=${{ secrets.STAGING_SSL_EMAIL }}' >> /opt/historian-app/staging/.env.staging"

      - name: Deploy on VPS
        run: |
          ssh root@217.154.198.215 'cd /opt/historian-app/staging && git pull origin development && docker-compose -f docker-compose.staging.yml pull && docker-compose -f docker-compose.staging.yml up -d'

      - name: Health check
        run: |
          ssh root@217.154.198.215 'curl -f http://localhost:8080/api/health || exit 1' 