name: Deploy to Staging

on:
  push:
    branches:
      - development

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy files to VPS
        run: |
          rsync -avz --exclude '.git' ./ root@217.154.198.215:/opt/historian-app/staging

      - name: Write .env.staging on server
        run: |
          ssh root@217.154.198.215 "cat > /opt/historian-app/staging/.env.staging <<EOF
NODE_ENV=staging
DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}
DATABASE_URL_UNPOOLED=${{ secrets.STAGING_DATABASE_URL_UNPOOLED }}
DATABASE_HOST=${{ secrets.STAGING_DATABASE_HOST }}
DATABASE_PORT=${{ secrets.STAGING_DATABASE_PORT }}
DATABASE_NAME=${{ secrets.STAGING_DATABASE_NAME }}
DATABASE_USERNAME=${{ secrets.STAGING_DATABASE_USERNAME }}
DATABASE_PASSWORD=${{ secrets.STAGING_DATABASE_PASSWORD }}
JWT_SECRET=${{ secrets.STAGING_JWT_SECRET }}
NEXT_PUBLIC_APP_URL=${{ secrets.STAGING_NEXT_PUBLIC_APP_URL }}
NEXT_PUBLIC_STRAPI_URL=${{ secrets.STAGING_NEXT_PUBLIC_STRAPI_URL }}
WORKOS_API_KEY=${{ secrets.STAGING_WORKOS_API_KEY }}
WORKOS_CLIENT_ID=${{ secrets.STAGING_WORKOS_CLIENT_ID }}
WORKOS_REDIRECT_URI=${{ secrets.STAGING_WORKOS_REDIRECT_URI }}
WORKOS_COOKIE_PASSWORD=${{ secrets.STAGING_WORKOS_COOKIE_PASSWORD }}
REDIS_PASSWORD=${{ secrets.STAGING_REDIS_PASSWORD }}
APP_KEYS=${{ secrets.STAGING_APP_KEYS }}
ENCRYPTION_KEY=${{ secrets.STAGING_ENCRYPTION_KEY }}
REDIS_URL=${{ secrets.STAGING_REDIS_URL }}
ADMIN_JWT_SECRET=${{ secrets.STAGING_ADMIN_JWT_SECRET }}
ADMIN_API_TOKEN_SALT=${{ secrets.STAGING_ADMIN_API_TOKEN_SALT }}
AUTHKIT_REDIRECT_URI=${{ secrets.STAGING_AUTHKIT_REDIRECT_URI }}
DOMAIN=${{ secrets.STAGING_DOMAIN }}
SSL_EMAIL=${{ secrets.STAGING_SSL_EMAIL }}
EOF"

      - name: Deploy on VPS
        run: |
          ssh root@217.154.198.215 'cd /opt/historian-app/staging && git pull origin development && docker-compose -f docker-compose.staging.yml pull && docker-compose -f docker-compose.staging.yml up -d'

      - name: Health check
        run: |
          ssh root@217.154.198.215 'curl -f http://localhost:8080/api/health || exit 1' 