name: Deploy to Staging

on:
  push:
    branches:
      - development

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy files to VPS
        run: |
          rsync -avz --exclude '.git' ./ root@217.154.198.215:/opt/historian-app/staging

      - name: Write .env.staging on server
        run: |
          ssh root@217.154.198.215 "cat > /opt/historian-app/staging/.env.staging << 'EOF'
NODE_ENV=staging
DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}
DATABASE_URL_UNPOOLED=${{ secrets.STAGING_DATABASE_URL_UNPOOLED }}
MYSQL_ROOT_PASSWORD=${{ secrets.STAGING_MYSQL_ROOT_PASSWORD }}
MYSQL_DATABASE=${{ secrets.STAGING_MYSQL_DATABASE }}
MYSQL_USER=${{ secrets.STAGING_MYSQL_USER }}
MYSQL_PASSWORD=${{ secrets.STAGING_MYSQL_PASSWORD }}
JWT_SECRET=${{ secrets.STAGING_JWT_SECRET }}
SMTP_HOST=${{ secrets.STAGING_SMTP_HOST }}
SMTP_PORT=${{ secrets.STAGING_SMTP_PORT }}
SMTP_USER=${{ secrets.STAGING_SMTP_USER }}
SMTP_PASS=${{ secrets.STAGING_SMTP_PASS }}
SMTP_FROM=${{ secrets.STAGING_SMTP_FROM }}
NEXTAUTH_URL=${{ secrets.STAGING_NEXTAUTH_URL }}
NEXTAUTH_SECRET=${{ secrets.STAGING_NEXTAUTH_SECRET }}
NEXT_PUBLIC_APP_URL=${{ secrets.STAGING_NEXT_PUBLIC_APP_URL }}
NEXT_PUBLIC_STRAPI_URL=${{ secrets.STAGING_NEXT_PUBLIC_STRAPI_URL }}
WORKOS_API_KEY=${{ secrets.STAGING_WORKOS_API_KEY }}
WORKOS_CLIENT_ID=${{ secrets.STAGING_WORKOS_CLIENT_ID }}
WORKOS_REDIRECT_URI=${{ secrets.STAGING_WORKOS_REDIRECT_URI }}
WORKOS_COOKIE_PASSWORD=${{ secrets.STAGING_WORKOS_COOKIE_PASSWORD }}
EOF"

      - name: Deploy on VPS
        run: |
          ssh root@217.154.198.215 'cd /opt/historian-app/staging && git pull origin development && docker-compose -f docker-compose.staging.yml pull && docker-compose -f docker-compose.staging.yml up -d'

      - name: Health check
        run: |
          ssh root@217.154.198.215 'curl -f http://localhost:8080/api/health || exit 1' 