name: Deploy to Staging

on:
  push:
    branches:
      - development

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Lint and Type check
        run: |
          npm run lint &
          npm run type-check &
          wait

      - name: Run tests
        run: npm test

      - name: Build application (skip for faster deployment)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED }}
          NODE_ENV: staging
          NEXT_PUBLIC_STRAPI_URL: https://staging.evidoxa.com/strapi
          NEXT_PUBLIC_IS_STAGING: true
        run: echo "Skipping local build - will build on VPS for faster deployment"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" > ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Write .env.staging on server
        run: |
          ssh root@217.154.198.215 "cat > /opt/historian-app/staging/.env.staging << 'EOF'
          NODE_ENV=staging
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DATABASE_URL_UNPOOLED=${{ secrets.DATABASE_URL_UNPOOLED }}
          DATABASE_HOST=${{ secrets.STRAPI_DB_HOST }}
          DATABASE_NAME=${{ secrets.STRAPI_DB_NAME }}
          DATABASE_USERNAME=${{ secrets.STRAPI_DB_USER }}
          DATABASE_PASSWORD=${{ secrets.STRAPI_DB_PASSWORD }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
          NEXT_PUBLIC_STRAPI_URL=${{ secrets.NEXT_PUBLIC_STRAPI_URL }}
          WORKOS_API_KEY=${{ secrets.WORKOS_API_KEY }}
          WORKOS_CLIENT_ID=${{ secrets.WORKOS_CLIENT_ID }}
          WORKOS_REDIRECT_URI=${{ secrets.WORKOS_REDIRECT_URI }}
          WORKOS_COOKIE_PASSWORD=${{ secrets.WORKOS_COOKIE_PASSWORD }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          APP_KEYS=${{ secrets.STRAPI_APP_KEYS }}
          ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          ADMIN_JWT_SECRET=${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
          ADMIN_API_TOKEN_SALT=${{ secrets.STRAPI_ADMIN_API_TOKEN_SALT }}
          ADMIN_TRANSFER_TOKEN_SALT=${{ secrets.STRAPI_ADMIN_TRANSFER_TOKEN_SALT }}
          AUTHKIT_REDIRECT_URI=${{ secrets.AUTHKIT_REDIRECT_URI }}
          DOMAIN=${{ secrets.DOMAIN }}
          SSL_EMAIL=${{ secrets.SSL_EMAIL }}
          EOF"

      - name: Show local nginx.conf before rsync
        run: |
          echo '--- LOCAL nginx.conf ---'
          cat ./nginx/nginx.staging.conf
          echo '--- LOCAL nginx.conf SHA256 ---'
          sha256sum ./nginx/nginx.staging.conf

      - name: Copy files to VPS
        run: |
          rsync -avz --exclude '.git' --exclude 'node_modules' --exclude '.next' --exclude 'dist' --exclude 'build' --exclude 'logs' --exclude 'test-results' --exclude 'playwright-report' ./ root@217.154.198.215:/opt/historian-app/staging

      - name: Show remote nginx.conf after rsync
        run: |
          ssh root@217.154.198.215 "echo '--- REMOTE nginx.conf ---' && cat /opt/historian-app/staging/nginx/nginx.staging.conf && echo '--- REMOTE nginx.conf SHA256 ---' && sha256sum /opt/historian-app/staging/nginx/nginx.staging.conf"

      - name: Show .env.staging on server
        run: |
          ssh root@217.154.198.215 "cat /opt/historian-app/staging/.env.staging"

      - name: Debug DATABASE_URL values
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"
          echo "DATABASE_URL_UNPOOLED=${{ secrets.DATABASE_URL_UNPOOLED }}"

      - name: Deploy on VPS
        run: |
          ssh root@217.154.198.215 "cd /opt/historian-app/staging && cp .env.staging .env && git pull origin development && docker-compose -f docker-compose.staging.yml down --remove-orphans && docker rm -f historian-redis-staging historian-certbot-staging historian_app_staging historian_strapi_staging historian_nginx_staging 2>/dev/null || true && docker-compose -f docker-compose.staging.yml build --no-cache && docker-compose -f docker-compose.staging.yml up -d"

      - name: Check deployment status
        run: |
          ssh root@217.154.198.215 'docker-compose -f /opt/historian-app/staging/docker-compose.staging.yml ps'

      - name: Health check
        run: |
          ssh root@217.154.198.215 'sleep 15 && curl -f http://localhost:8080/api/health || exit 1' 

      - name: Show container logs if health check fails
        if: failure()
        run: |
          ssh root@217.154.198.215 'docker-compose -f /opt/historian-app/staging/docker-compose.staging.yml ps'